INSERT INTO tables (NUMBER_TABLE) VALUES (1);
INSERT INTO tables (NUMBER_TABLE) VALUES (2);
INSERT INTO tables (NUMBER_TABLE) VALUES (3);
INSERT INTO tables (NUMBER_TABLE) VALUES (4);
INSERT INTO tables (NUMBER_TABLE) VALUES (5);
INSERT INTO tables (NUMBER_TABLE) VALUES (6);
INSERT INTO tables (NUMBER_TABLE) VALUES (7);
INSERT INTO tables (NUMBER_TABLE) VALUES (8);
INSERT INTO tables (NUMBER_TABLE) VALUES (9);
INSERT INTO tables (NUMBER_TABLE) VALUES (10);
INSERT INTO tables (NUMBER_TABLE) VALUES (11);

INSERT INTO users(EMAIL, PASSWORD, USERNAME) VALUES ('admin@admin.com', 'admin', 'admin');
INSERT INTO user_roles(USER_ID, ROLES) VALUES (1, 'ROLE_ADMIN');


INSERT INTO meals(NAME, PRICE, TYPE) VALUES ('Szakszuka', 15.0,'BREAKFAST');
INSERT INTO meals(NAME, PRICE, TYPE) VALUES ('Jajecznica', 10.5,'BREAKFAST');
INSERT INTO meals(NAME, PRICE, TYPE) VALUES ('Jajecznica na ostro', 10.80,'BREAKFAST');
INSERT INTO meals(NAME, PRICE, TYPE) VALUES ('Kanapka z szynka',6.50 ,'BREAKFAST');
INSERT INTO meals(NAME, PRICE, TYPE) VALUES ('Kanapka wege',7.00 ,'BREAKFAST');

INSERT INTO meals(NAME, PRICE, TYPE) VALUES ('Schabowy', 8.00,'DINNER');
INSERT INTO meals(NAME, PRICE, TYPE) VALUES ('Gotowane ziemniaki', 5.00,'DINNER');
INSERT INTO meals(NAME, PRICE, TYPE) VALUES ('Frytki', 6.00,'DINNER');
INSERT INTO meals(NAME, PRICE, TYPE) VALUES ('Surówka', 3.00,'DINNER');
INSERT INTO meals(NAME, PRICE, TYPE) VALUES ('Salatka', 4.50,'DINNER');


INSERT INTO meals(NAME, PRICE, TYPE) VALUES ('Cebulowa',6.50 ,'SOUP');
INSERT INTO meals(NAME, PRICE, TYPE) VALUES ('Barszcz', 6.00,'SOUP');
INSERT INTO meals(NAME, PRICE, TYPE) VALUES ('Zurek', 6.00,'SOUP');
INSERT INTO meals(NAME, PRICE, TYPE) VALUES ('Botwinka', 6.00,'SOUP');
INSERT INTO meals(NAME, PRICE, TYPE) VALUES ('Pomidorowa', 6.00,'SOUP');


INSERT INTO meals(NAME, PRICE, TYPE) VALUES ('Zapiekanka',7.50 ,'SUPPER');
INSERT INTO meals(NAME, PRICE, TYPE) VALUES ('Kanapka z majonezem', 3.0,'SUPPER');
INSERT INTO meals(NAME, PRICE, TYPE) VALUES ('Piwo', 5.0,'SUPPER');
INSERT INTO meals(NAME, PRICE, TYPE) VALUES ('Pizza margerita', 6.09,'SUPPER');
INSERT INTO meals(NAME, PRICE, TYPE) VALUES ('Pizza carbonara', 6.09,'SUPPER');
